sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t yjkim21/test -f Dockerfile.dev .

script:
  - docker run -e CI=ture yjkim21/test npm run test -- --coverage

after_success:
  - echo "Test Sucess"


deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "test"
  env: test-env
  bucket_name: "elasticbeanstalk-ap-northeast-2-164394666548"
  bucket_path: "test"
  on
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY